CREATE TABLE USUARIO (
    id_usuario NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(30) NOT NULL UNIQUE,
    nombre_completo VARCHAR2(50) NOT NULL,
    biografia VARCHAR2(150),
    esta_privada CHAR(1) DEFAULT 'N' NOT NULL CHECK (esta_privada IN ('S', 'N')),
    fecha_creacion DATE DEFAULT SYSDATE NOT NULL
);

CREATE TABLE FOTO (
    id_foto NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    url_imagen VARCHAR2(500) NOT NULL,
    tipo_imagen VARCHAR2(130) NOT NULL,
    fecha_creacion TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE REEL (
    id_reel NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    duracion_segundos NUMBER NOT NULL,
    fecha_reel TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE HISTORIA (
    id_historia NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    duracion_segundos NUMBER NOT NULL
);

CREATE TABLE PUBLICACION (
    id_publicacion NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario NUMBER NOT NULL REFERENCES USUARIO(id_usuario),
    id_foto NUMBER REFERENCES FOTO(id_foto),
    id_reel NUMBER REFERENCES REEL(id_reel),
    id_historia NUMBER REFERENCES HISTORIA(id_historia),
    texto VARCHAR2(2200),
    fecha_publicacion TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE COMENTARIO (
    id_comentario NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario NUMBER NOT NULL REFERENCES USUARIO(id_usuario),
    id_publicacion NUMBER NOT NULL REFERENCES PUBLICACION(id_publicacion),
    comentario VARCHAR2(150) NOT NULL,
    fecha_comentario TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE MEGUSTA (
    id_megusta NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario NUMBER NOT NULL REFERENCES USUARIO(id_usuario),
    id_publicacion NUMBER NOT NULL REFERENCES PUBLICACION(id_publicacion),
    fecha_megusta DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT uq_megusta UNIQUE (id_usuario, id_publicacion)
);

CREATE TABLE GUARDADO (
    id_guardado NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_publicacion NUMBER NOT NULL REFERENCES PUBLICACION(id_publicacion),
    id_usuario NUMBER NOT NULL REFERENCES USUARIO(id_usuario),
    fecha_guardado TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_guardado UNIQUE (id_usuario, id_publicacion)
);

CREATE TABLE ENVIVO (
    id_envivo NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario NUMBER NOT NULL REFERENCES USUARIO(id_usuario),
    titulo VARCHAR2(70) NOT NULL,
    duracion_segundos NUMBER,
    programar_fecha_video TIMESTAMP NOT NULL
);

CREATE TABLE GRUPO_CHAT (
    id_grupo_chat NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_grupo VARCHAR2(70) NOT NULL,
    id_creador NUMBER NOT NULL REFERENCES USUARIO(id_usuario),
    fecha_creacion TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE CHAT_USUARIO (
    id_chat_usuario NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario NUMBER NOT NULL REFERENCES USUARIO(id_usuario),
    id_destinatario NUMBER REFERENCES USUARIO(id_usuario),
    id_grupo_chat NUMBER REFERENCES GRUPO_CHAT(id_grupo_chat),
    mensaje VARCHAR2(1000) NOT NULL,
    fecha_mensaje TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

INSERT INTO USUARIO (id_usuario, username, nombre_completo, biografia, esta_privada, fecha_creacion)
VALUES (1, 'lucia.fotos', 'Lucia Torres', 'Fotografia, viajes y atardeceres.', 'N', DATE '2026-10-01');
INSERT INTO USUARIO (id_usuario, username, nombre_completo, biografia, esta_privada, fecha_creacion)
VALUES (2, 'mateo.beats', 'Mateo Rojas', 'Productor musical. Siempre creando algo nuevo.', 'N', DATE '2026-10-01');
INSERT INTO USUARIO (id_usuario, username, nombre_completo, biografia, esta_privada, fecha_creacion)
VALUES (3, 'sofia.rutas', 'Sofia Vega', 'Senderismo, naturaleza y cafe.', 'S', DATE '2026-10-01');

INSERT INTO FOTO (id_foto, url_imagen, tipo_imagen, fecha_creacion)
VALUES (1, 'https://example.com/fotos/atardecer.jpg', 'image/jpeg', TIMESTAMP '2026-10-06 10:00:00');
INSERT INTO FOTO (id_foto, url_imagen, tipo_imagen, fecha_creacion)
VALUES (2, 'https://example.com/fotos/estudio.jpg', 'image/jpeg', TIMESTAMP '2026-10-06 10:00:00');
INSERT INTO FOTO (id_foto, url_imagen, tipo_imagen, fecha_creacion)
VALUES (3, 'https://example.com/fotos/montana.jpg', 'image/jpeg', TIMESTAMP '2026-10-06 10:00:00');

INSERT INTO REEL (id_reel, duracion_segundos, fecha_reel)
VALUES (1, 30, TIMESTAMP '2026-10-06 11:00:00');
INSERT INTO REEL (id_reel, duracion_segundos, fecha_reel)
VALUES (2, 45, TIMESTAMP '2026-10-06 11:00:00');
INSERT INTO REEL (id_reel, duracion_segundos, fecha_reel)
VALUES (3, 60, TIMESTAMP '2026-10-06 11:00:00');

INSERT INTO HISTORIA (id_historia, duracion_segundos)
VALUES (1, 15);
INSERT INTO HISTORIA (id_historia, duracion_segundos)
VALUES (2, 20);
INSERT INTO HISTORIA (id_historia, duracion_segundos)
VALUES (3, 15);

INSERT INTO PUBLICACION (id_publicacion, id_usuario, id_foto, texto, fecha_publicacion)
VALUES (1, 1, 1, 'Un atardecer para recordar.', TIMESTAMP '2026-10-06 11:30:00');
INSERT INTO PUBLICACION (id_publicacion, id_usuario, id_foto, texto, fecha_publicacion)
VALUES (2, 2, 2, 'Trabajando en mi proxima cancion.', TIMESTAMP '2026-10-06 11:30:00');
INSERT INTO PUBLICACION (id_publicacion, id_usuario, id_foto, texto, fecha_publicacion)
VALUES (3, 3, 3, 'Llegamos a la cima.', TIMESTAMP '2026-10-06 11:30:00');
INSERT INTO PUBLICACION (id_publicacion, id_usuario, id_reel, texto, fecha_publicacion)
VALUES (4, 1, 1, 'Recorriendo la ciudad con mi camara.', TIMESTAMP '2026-10-06 12:30:00');
INSERT INTO PUBLICACION (id_publicacion, id_usuario, id_reel, texto, fecha_publicacion)
VALUES (5, 2, 2, 'Asi construyo una bateria desde cero.', TIMESTAMP '2026-10-06 12:30:00');
INSERT INTO PUBLICACION (id_publicacion, id_usuario, id_reel, texto, fecha_publicacion)
VALUES (6, 3, 3, 'Un minuto de nuestra ultima caminata.', TIMESTAMP '2026-10-06 12:30:00');
INSERT INTO PUBLICACION (id_publicacion, id_usuario, id_historia, texto, fecha_publicacion)
VALUES (7, 1, 1, 'Mi rincon favorito de la ciudad.', TIMESTAMP '2026-10-06 13:30:00');
INSERT INTO PUBLICACION (id_publicacion, id_usuario, id_historia, texto, fecha_publicacion)
VALUES (8, 2, 2, 'Un adelanto del nuevo beat.', TIMESTAMP '2026-10-06 13:30:00');
INSERT INTO PUBLICACION (id_publicacion, id_usuario, id_historia, texto, fecha_publicacion)
VALUES (9, 3, 3, 'Cafe antes de salir a caminar.', TIMESTAMP '2026-10-06 13:30:00');

INSERT INTO COMENTARIO (id_comentario, id_usuario, id_publicacion, comentario, fecha_comentario)
VALUES (1, 2, 1, 'Que buena luz tiene esa foto.', TIMESTAMP '2026-10-06 14:00:00');
INSERT INTO COMENTARIO (id_comentario, id_usuario, id_publicacion, comentario, fecha_comentario)
VALUES (2, 3, 2, 'Espero escuchar la cancion completa.', TIMESTAMP '2026-10-06 14:00:00');
INSERT INTO COMENTARIO (id_comentario, id_usuario, id_publicacion, comentario, fecha_comentario)
VALUES (3, 1, 3, 'Hermoso paisaje, Sofia.', TIMESTAMP '2026-10-06 14:00:00');

INSERT INTO MEGUSTA (id_megusta, id_usuario, id_publicacion, fecha_megusta)
VALUES (1, 2, 1, DATE '2026-10-06');
INSERT INTO MEGUSTA (id_megusta, id_usuario, id_publicacion, fecha_megusta)
VALUES (2, 3, 2, DATE '2026-10-06');
INSERT INTO MEGUSTA (id_megusta, id_usuario, id_publicacion, fecha_megusta)
VALUES (3, 1, 3, DATE '2026-10-06');
INSERT INTO MEGUSTA (id_megusta, id_usuario, id_publicacion, fecha_megusta)
VALUES (4, 1, 5, DATE '2026-10-06');
INSERT INTO MEGUSTA (id_megusta, id_usuario, id_publicacion, fecha_megusta)
VALUES (5, 2, 6, DATE '2026-10-06');
INSERT INTO MEGUSTA (id_megusta, id_usuario, id_publicacion, fecha_megusta)
VALUES (6, 3, 4, DATE '2026-10-06');

INSERT INTO GUARDADO (id_guardado, id_publicacion, id_usuario, fecha_guardado)
VALUES (1, 3, 1, TIMESTAMP '2026-10-06 14:10:00');
INSERT INTO GUARDADO (id_guardado, id_publicacion, id_usuario, fecha_guardado)
VALUES (2, 4, 2, TIMESTAMP '2026-10-06 14:10:00');
INSERT INTO GUARDADO (id_guardado, id_publicacion, id_usuario, fecha_guardado)
VALUES (3, 5, 3, TIMESTAMP '2026-10-06 14:10:00');

INSERT INTO ENVIVO (id_envivo, id_usuario, titulo, duracion_segundos, programar_fecha_video)
VALUES (1, 1, 'Consejos de fotografia', 1800, TIMESTAMP '2026-10-07 18:00:00');
INSERT INTO ENVIVO (id_envivo, id_usuario, titulo, duracion_segundos, programar_fecha_video)
VALUES (2, 2, 'Creando un beat en directo', 1800, TIMESTAMP '2026-10-07 19:00:00');
INSERT INTO ENVIVO (id_envivo, id_usuario, titulo, duracion_segundos, programar_fecha_video)
VALUES (3, 3, 'Preparando la proxima ruta', 1800, TIMESTAMP '2026-10-07 20:00:00');

INSERT INTO GRUPO_CHAT (id_grupo_chat, nombre_grupo, id_creador, fecha_creacion)
VALUES (1, 'Amigos creativos', 1, TIMESTAMP '2026-10-06 09:00:00');

INSERT INTO CHAT_USUARIO (id_chat_usuario, id_usuario, id_destinatario, mensaje, fecha_mensaje)
VALUES (1, 1, 2, 'Mateo, me gusto tu nuevo beat.', TIMESTAMP '2026-10-06 15:00:00');
INSERT INTO CHAT_USUARIO (id_chat_usuario, id_usuario, id_destinatario, mensaje, fecha_mensaje)
VALUES (2, 2, 3, 'Sofia, cuando es la proxima caminata?', TIMESTAMP '2026-10-06 15:00:00');
INSERT INTO CHAT_USUARIO (id_chat_usuario, id_usuario, id_destinatario, mensaje, fecha_mensaje)
VALUES (3, 3, 1, 'Lucia, llevas tu camara el sabado?', TIMESTAMP '2026-10-06 15:00:00');
INSERT INTO CHAT_USUARIO (id_chat_usuario, id_usuario, id_grupo_chat, mensaje, fecha_mensaje)
VALUES (4, 1, 1, 'Bienvenidos al grupo.', TIMESTAMP '2026-10-06 15:30:00');
INSERT INTO CHAT_USUARIO (id_chat_usuario, id_usuario, id_grupo_chat, mensaje, fecha_mensaje)
VALUES (5, 2, 1, 'Podemos organizar una salida creativa.', TIMESTAMP '2026-10-06 15:30:00');
INSERT INTO CHAT_USUARIO (id_chat_usuario, id_usuario, id_grupo_chat, mensaje, fecha_mensaje)
VALUES (6, 3, 1, 'Me sumo! Hagamos fotos y musica.', TIMESTAMP '2026-10-06 15:30:00');

COMMIT;
